export const defaultConstant = {
    LOGIN: 'Login',
    REGISTER: 'Register',
    NEWUSER: 'New User',
    ALREADYACCOUNT: 'Already have an account?',
    CONTACT: 'Contact',
    DASHBOARD: 'Dashboard',
    HOMEPAGE: 'Homepage',
    LOGOUT: 'Logout',
    WELCOME: 'Welcome',
    PROFILE: 'Profile',
    PATIENT: 'Patient',
    DOCTOR: 'Doctor',
    ADMIN: 'Admin',
    USER: 'User',
    DOCTORREGISTRATION: 'Doctor Registration',
    PATIENTREGISTRATION: 'Patient Registration',
    ADMINREGISTRATION: 'Admin Registration',
    NAME: 'Name',
    EMAIL: 'Email',
    PHONENUMBER: 'Phone Number',
    PASSWORD: 'Password',
    CONFIRMPASSWORD: 'Confirm Password',
    CONTACTUS: 'Contact Us',
    MESSAGE: 'Message',
    SUBMIT: 'Submit',
    USERNAME: 'Username',
    LOGINERROR: 'Login Error',
    REGISTERERROR: 'Register Error',
    LOGINERRORMSG: 'Invalid username or password',
    SERVICES: 'Services',
    HEALTHTOPICS: 'Health Topics',
    HEALTHCAREPORTAL: 'Healthcare Portal'
}